---
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "api-stats-chart.fullname" . }}-secrets
type: Opaque
data:
    YOUTUBE_API_KEY: "{{ .Values.apiStatsSettings.ytAPIKey | default "" | b64enc }}"
    YOUTUBE_CHANNEL_ID: "{{ .Values.apiStatsSettings.ytChannelID | default "" | b64enc }}"